groups:
- name: example
  rules:

  - alert: service_down
    expr: up{job="metrics"} == 0
    labels:
      severity: major
    annotations:
      description: Service {{ $labels.instance }} is unavailable.
      value: DOWN ({{ $value }})
